# Generated by Django 4.1.4 on 2022-12-21 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_ingredients_family_dish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="member",
        ),
        migrations.AddField(
            model_name="family",
            name="member",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Family Member"
            ),
        ),
    ]
