# Generated by Django 4.1.4 on 2022-12-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_family_member_family_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dishes_chosen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.dish",
                        verbose_name="Dish chosen by User",
                    ),
                ),
            ],
        ),
    ]
