# Generated by Django 4.1.4 on 2022-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_dishes_chosen_dish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishes_chosen",
            name="dishes_chosen",
            field=models.ManyToManyField(
                blank=True, to="users.dish", verbose_name="Dishes To Shop"
            ),
        ),
    ]
