# Generated by Django 4.1.4 on 2023-01-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_dishes_chosen_dishes_chosen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shoppinglist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.family",
                    ),
                ),
                ("ingredients", models.ManyToManyField(to="users.ingredients")),
            ],
        ),
        migrations.AddField(
            model_name="dishes_chosen",
            name="ingredients_chosen",
            field=models.ManyToManyField(
                blank=True, to="users.ingredients", verbose_name="ingredients at home"
            ),
        ),
        migrations.DeleteModel(
            name="Checklist",
        ),
    ]
