# Generated by Django 4.1.4 on 2023-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_shoppinglist_dishes_chosen_ingredients_chosen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishes_chosen",
            name="ingredients_chosen",
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="ingredients",
            field=models.ManyToManyField(blank=True, to="users.ingredients"),
        ),
    ]
