# Generated by Django 4.1.4 on 2023-01-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_dishes_chosen_ingredients_chosen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="ingredients_added",
            field=models.ManyToManyField(
                blank=True,
                related_name="Basket",
                to="users.ingredients",
                verbose_name="Items added",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, to="users.ingredients", verbose_name="Items on List"
            ),
        ),
    ]
