# Generated by Django 4.1.4 on 2023-01-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_shoppinglist_ingredients_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, to="users.ingredients", verbose_name="Items to shop"
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="ingredients_added",
            field=models.ManyToManyField(
                blank=True,
                related_name="Basket",
                to="users.ingredients",
                verbose_name="Items in basket",
            ),
        ),
    ]
